database:
  host: localhost
  port: 5433
  user: postgres
  password: password
  dbname: exam_app

nats:
  url: nats://localhost:4222

api:
  direct_port: 8080
  queue_port: 8081

worker:
  count: 10
  batch_size: 100
